# Malnati/templateer@v1.0.1
name: "Templateer"
description: "Render timeline messages, checklists, and status reports consistently across workflows."
author: "Ricardo Malnati"

branding:
  icon: "file-text"
  color: "blue"

inputs:
  template:
    description: "Template path."
    required: true
  result:
    description: "Output file path."
    required: true
  debug:
    description: "If 'true', prints the exported variables."
    required: false
    default: "false"

outputs:
  path:
    description: "Rendered file path."
    value: ${{ steps.replacer.outputs.path }}
  body:
    description: "Rendered content."
    value: ${{ steps.replacer.outputs.body }}

runs:
  using: "composite"
  steps:
    - name: Exporter
      id: exporter
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}
      run: |
        set -euo pipefail
        echo "🪄 Exporting variables to the template"
        env | grep -v '^GITHUB_' | while IFS='=' read -r key value; do
          if [ "${DEBUG:-false}" = "true" ]; then
            printf '%s=%s\n' "$key" "$value"
          fi
          printf '%s=%s\n' "$key" "$value" >> "$GITHUB_ENV"
        done

    - name: "📄 Render"
      id: replacer
      shell: bash
      env:
        TEMPLATE_RESOLVED: ${{ inputs.template }}
        OUTPUT_RESOLVED: ${{ inputs.result }}
      run: |
        set -euo pipefail
        envsubst < "$TEMPLATE_RESOLVED" > "$OUTPUT_RESOLVED"
        echo "path=$OUTPUT_RESOLVED" >> "$GITHUB_OUTPUT"
        {
          printf 'body<<EOF\n'
          cat "$OUTPUT_RESOLVED"
          printf '\nEOF\n'
        } >> "$GITHUB_OUTPUT"
